title: Puggera Ponanna
description: 'Tech Blog'
url: 'puggeraponanna.github.io'
baseurl: ''
google_analytics: UA-169610915-1
formspree: https://formspree.io/xpzyrvye

author:
  name: Puggera Ponanna
  email: puggeraponanna@tuta.io

collections:
  posts:
    output: true
    permalink: /:collection/:title

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
